[[Opus]]
arch = "aarch64"
git-tree-sha1 = "83ff444c229f9dd64a13999123a4eb14e632d67a"
os = "macos"

    [[Opus.download]]
    sha256 = "cece83631da64c3a0ea616c11cc657973d846524d2781c57fecbd4df27b3f1a5"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.3+0/Opus.v1.3.3.aarch64-apple-darwin.tar.gz"
[[Opus]]
arch = "aarch64"
git-tree-sha1 = "dcc52cd24bf5bffaf7c7958276006bfcf0cc4772"
libc = "glibc"
os = "linux"

    [[Opus.download]]
    sha256 = "5b63189290485ee546e64187f755e7d59e7ba7152328356d22772e35316fb877"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.3+0/Opus.v1.3.3.aarch64-linux-gnu.tar.gz"
[[Opus]]
arch = "aarch64"
git-tree-sha1 = "914b3f8df84a4cccc635a15c6f89a05431391a19"
libc = "musl"
os = "linux"

    [[Opus.download]]
    sha256 = "f09e5fc23c94496de7318d5fdfed3aaf08df49a0abaf332e54f25bd0560f1f69"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.3+0/Opus.v1.3.3.aarch64-linux-musl.tar.gz"
[[Opus]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4378b25d675c4f473a632670c3274f80eb8d4c1f"
libc = "glibc"
os = "linux"

    [[Opus.download]]
    sha256 = "bdb2bffb0cfed058b88120dc2f08c9603146e1c6de5bd7e95aae40116e05e902"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.3+0/Opus.v1.3.3.armv6l-linux-gnueabihf.tar.gz"
[[Opus]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "972295a2e7c93ff1c16b5a60a12ebea466d57b43"
libc = "musl"
os = "linux"

    [[Opus.download]]
    sha256 = "85e9437c30351904661eebb10c2c71b85fe3f48cc12f56b3d4ce3243a1e5ca7e"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.3+0/Opus.v1.3.3.armv6l-linux-musleabihf.tar.gz"
[[Opus]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0fde0d92bb3aa2b4541a8f2eb71631fd3a3b7ef5"
libc = "glibc"
os = "linux"

    [[Opus.download]]
    sha256 = "84592dc38e6e185066151159a2e4ec997bb955d9a7ac58c1e332b38c61e56c5f"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.3+0/Opus.v1.3.3.armv7l-linux-gnueabihf.tar.gz"
[[Opus]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1ae0b689728106a26af934161aa009019261ec28"
libc = "musl"
os = "linux"

    [[Opus.download]]
    sha256 = "238690b01726f6a8dc0fea0091ec0e37c8143bca926436d66c549baebef7fe2e"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.3+0/Opus.v1.3.3.armv7l-linux-musleabihf.tar.gz"
[[Opus]]
arch = "i686"
git-tree-sha1 = "3e49abe5b11a2511b91a915288a8cda016fab7ca"
libc = "glibc"
os = "linux"

    [[Opus.download]]
    sha256 = "9e5521160728963a92fefd5f7e8a9d805e2446fca361a337cfe4bbf61d3503c4"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.3+0/Opus.v1.3.3.i686-linux-gnu.tar.gz"
[[Opus]]
arch = "i686"
git-tree-sha1 = "030ccf8d47db89dfedc3ab8ebe9d3da2c8e74d86"
libc = "musl"
os = "linux"

    [[Opus.download]]
    sha256 = "065408b7edb936e44f9c19529f37033e045b1d96b443b9a5a64f0b2676e35ca5"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.3+0/Opus.v1.3.3.i686-linux-musl.tar.gz"
[[Opus]]
arch = "i686"
git-tree-sha1 = "d148cde3407d482000483264755133452e71ac7e"
os = "windows"

    [[Opus.download]]
    sha256 = "087b08a5a93de734f025b7e640069af98f52a680eba71406247d392b3d42f102"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.3+0/Opus.v1.3.3.i686-w64-mingw32.tar.gz"
[[Opus]]
arch = "powerpc64le"
git-tree-sha1 = "3f9ccb215d21d2a72108b6cb66dce1969102f43f"
libc = "glibc"
os = "linux"

    [[Opus.download]]
    sha256 = "4ad64b33c1e204882d9b71037af52cafcdbb43586ea676dccaf0d1f2cdede587"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.3+0/Opus.v1.3.3.powerpc64le-linux-gnu.tar.gz"
[[Opus]]
arch = "x86_64"
git-tree-sha1 = "a92f4b258395c4541e7553f9846342807185d78d"
os = "macos"

    [[Opus.download]]
    sha256 = "65f00cae408eb11b9a2a066618416be72d57f2f074d8de81c61c721c0b76fbd1"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.3+0/Opus.v1.3.3.x86_64-apple-darwin.tar.gz"
[[Opus]]
arch = "x86_64"
git-tree-sha1 = "85dab0a3f6b9cc2e5d61165ee376bf46260812a4"
libc = "glibc"
os = "linux"

    [[Opus.download]]
    sha256 = "bcacd0347daeacd9cbf71821b740a61f9abcab117b1eeed74516c03088b40815"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.3+0/Opus.v1.3.3.x86_64-linux-gnu.tar.gz"
[[Opus]]
arch = "x86_64"
git-tree-sha1 = "3bfe6e7067dd50c9a01d7f8c4edf862ad6fa9d85"
libc = "musl"
os = "linux"

    [[Opus.download]]
    sha256 = "34c41b61dcdec47557dddb05de00b632138bbf3f06b8384e4b50f145f9bb5aa9"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.3+0/Opus.v1.3.3.x86_64-linux-musl.tar.gz"
[[Opus]]
arch = "x86_64"
git-tree-sha1 = "bdbeea3a53d73082330c1b82920f36b0cccb3eca"
os = "freebsd"

    [[Opus.download]]
    sha256 = "743462117ce0abbc37b2408d08809b98b6a3770297f7d7cd88a6c1ae691c1f30"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.3+0/Opus.v1.3.3.x86_64-unknown-freebsd.tar.gz"
[[Opus]]
arch = "x86_64"
git-tree-sha1 = "fb9a8380891be8f2464dd29539924a67e159c5e7"
os = "windows"

    [[Opus.download]]
    sha256 = "827739c1a4ea410fb5e6d7532ccac436bfbbfc9fb75475f204658cd650b16731"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.3.3+0/Opus.v1.3.3.x86_64-w64-mingw32.tar.gz"
