[[Opus]]
arch = "aarch64"
git-tree-sha1 = "ab9383a824148af6327107975ae00b323e81fe2e"
os = "macos"

    [[Opus.download]]
    sha256 = "11baea3fb390bd6e3f852a581ea385b372465bb7f2f8257a57647d84b283c891"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.5.2+0/Opus.v1.5.2.aarch64-apple-darwin.tar.gz"
[[Opus]]
arch = "aarch64"
git-tree-sha1 = "b24a1098abebf759ff44ffff3046d2012824f66a"
libc = "glibc"
os = "linux"

    [[Opus.download]]
    sha256 = "15259aef0875489b77fd01db7183cf264454b104f90a270f709f30905fe86a21"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.5.2+0/Opus.v1.5.2.aarch64-linux-gnu.tar.gz"
[[Opus]]
arch = "aarch64"
git-tree-sha1 = "a04c91426124244a040fb216a7939830351406e1"
libc = "musl"
os = "linux"

    [[Opus.download]]
    sha256 = "fa6b571a3bc2f90474f819e2a94b31e9699aeb51ca16cbdb4b009d980b7e7fa7"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.5.2+0/Opus.v1.5.2.aarch64-linux-musl.tar.gz"
[[Opus]]
arch = "aarch64"
git-tree-sha1 = "26441d823ea4ef04f1345e320518e16a1dfaabee"
os = "freebsd"

    [[Opus.download]]
    sha256 = "ed00b89a489d0bafdc62ac0d050b0268d98ae91bcaec00d4a2fd986318d83f88"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.5.2+0/Opus.v1.5.2.aarch64-unknown-freebsd.tar.gz"
[[Opus]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a056636c53cdafc4a3c214abb0fa6f90fa5e01a5"
libc = "glibc"
os = "linux"

    [[Opus.download]]
    sha256 = "8a0e06c1ed788f74fe7ac4d9f14ea22911d4a85302eacb1cabbfb10217bd1507"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.5.2+0/Opus.v1.5.2.armv6l-linux-gnueabihf.tar.gz"
[[Opus]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f66a745c357f9c7570e6574282e37b7a1263c0cf"
libc = "musl"
os = "linux"

    [[Opus.download]]
    sha256 = "aac7f47a8ee052483befed0fc4f3e4f5279c6550b9a56fd5339e20aac767e797"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.5.2+0/Opus.v1.5.2.armv6l-linux-musleabihf.tar.gz"
[[Opus]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "465bf411f089bffcf9d79402acb754624e96cbc6"
libc = "glibc"
os = "linux"

    [[Opus.download]]
    sha256 = "6757882f34e2719bcb31ecb7cb5c876a5115351d9a14bdb040ab023cdaca7cfa"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.5.2+0/Opus.v1.5.2.armv7l-linux-gnueabihf.tar.gz"
[[Opus]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e1d5bb8581acf7e97d77615e0af0853e4b61a368"
libc = "musl"
os = "linux"

    [[Opus.download]]
    sha256 = "375eb79e4213d8760f75ae1553ac383cef5c544750a84be00bca3844fcbc837d"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.5.2+0/Opus.v1.5.2.armv7l-linux-musleabihf.tar.gz"
[[Opus]]
arch = "i686"
git-tree-sha1 = "c13cdd9c3f69c7edb5eeab278966a963ac018603"
libc = "glibc"
os = "linux"

    [[Opus.download]]
    sha256 = "816214a26cc537c99ad2f1fb0d721a334e3f4a9d95651914a2b2d85883ce6ab8"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.5.2+0/Opus.v1.5.2.i686-linux-gnu.tar.gz"
[[Opus]]
arch = "i686"
git-tree-sha1 = "bbf9e2429c19ba465a8809f5fc15558bf765d210"
libc = "musl"
os = "linux"

    [[Opus.download]]
    sha256 = "570e03956e67091ec885bac23a868c624cba1973e4d568d0af0bc3469dbee773"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.5.2+0/Opus.v1.5.2.i686-linux-musl.tar.gz"
[[Opus]]
arch = "i686"
git-tree-sha1 = "0bd5052901e29ce772b57e3b5439c624abac0006"
os = "windows"

    [[Opus.download]]
    sha256 = "5549fd25f3f72f253794c5297a27fb471280353a9a16ffb597dfcd0591546989"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.5.2+0/Opus.v1.5.2.i686-w64-mingw32.tar.gz"
[[Opus]]
arch = "powerpc64le"
git-tree-sha1 = "7d49647d050beb6093d9f3f6a793bc4449d9827b"
libc = "glibc"
os = "linux"

    [[Opus.download]]
    sha256 = "d33f477b652abedb75a0d4d21d3ebe9c56ba767edf4ba1cd8bb4ada99eb2e9e9"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.5.2+0/Opus.v1.5.2.powerpc64le-linux-gnu.tar.gz"
[[Opus]]
arch = "riscv64"
git-tree-sha1 = "f67250d9fc40a868a8c40dcd9ba60fe3b1888194"
libc = "glibc"
os = "linux"

    [[Opus.download]]
    sha256 = "0fe2866dea6ea860a3e0344099de1b93f36fe1e13591f81b9611c360d53b82ff"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.5.2+0/Opus.v1.5.2.riscv64-linux-gnu.tar.gz"
[[Opus]]
arch = "x86_64"
git-tree-sha1 = "3f0cb08b668fb6917eb179f67bfc88619089a3e3"
os = "macos"

    [[Opus.download]]
    sha256 = "d55397e04586e4dfed857970e16ed3a2707f9efc386458d7491ccbe343ec4916"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.5.2+0/Opus.v1.5.2.x86_64-apple-darwin.tar.gz"
[[Opus]]
arch = "x86_64"
git-tree-sha1 = "b4d9e913014918426c3ca714a536e10b9f54c784"
libc = "glibc"
os = "linux"

    [[Opus.download]]
    sha256 = "6c149a1c03ce013c85569961a0cf98b6eaad6313826f58572676ac67a5805df6"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.5.2+0/Opus.v1.5.2.x86_64-linux-gnu.tar.gz"
[[Opus]]
arch = "x86_64"
git-tree-sha1 = "8b0685e9301a81c234c5773f0e645dca3424b790"
libc = "musl"
os = "linux"

    [[Opus.download]]
    sha256 = "a15457512d7cc93dcbdb2624ef8894f00905bd72233ffdc6c788e00ac5c9e4d4"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.5.2+0/Opus.v1.5.2.x86_64-linux-musl.tar.gz"
[[Opus]]
arch = "x86_64"
git-tree-sha1 = "a1e92ccb3d8d702f79cce6e5ecf85cc9cbd1f155"
os = "freebsd"

    [[Opus.download]]
    sha256 = "10243553a671023c25e7046ba5820f557d3f6616204ce22e0fbd72767970f600"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.5.2+0/Opus.v1.5.2.x86_64-unknown-freebsd.tar.gz"
[[Opus]]
arch = "x86_64"
git-tree-sha1 = "7e207f56275705f9cbc88b826acd28ea0e40f1ae"
os = "windows"

    [[Opus.download]]
    sha256 = "d3f875b42d16f73bbdc5b07a538150a32165e0c42a5675c1de037d1d38381cc2"
    url = "https://github.com/JuliaBinaryWrappers/Opus_jll.jl/releases/download/Opus-v1.5.2+0/Opus.v1.5.2.x86_64-w64-mingw32.tar.gz"
